# Generated by Django 3.0.4 on 2020-03-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('mule_for', models.CharField(blank=True, max_length=255, null=True)),
                ('character_main', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CharacterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.CharField(max_length=255)),
                ('data_type_name', models.CharField(max_length=50)),
                ('data_type_category', models.CharField(max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
            ],
            options={
                'ordering': ['data_type_category', 'data_type_name'],
            },
        ),
    ]
