# Generated by Django 3.0.2 on 2020-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200301_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdataset',
            name='data_value',
            field=models.CharField(max_length=255),
        ),
    ]
