# Generated by Django 3.0.2 on 2020-03-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20200301_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterdataset',
            options={'ordering': ['data_value']},
        ),
    ]
