# Generated by Django 3.0.2 on 2020-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20200301_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'ordering': ['type_name']},
        ),
    ]
