# Generated by Django 3.0.2 on 2020-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20200301_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='type_category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
