# Generated by Django 3.0.2 on 2020-03-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20200301_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='type_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='type_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
