# Generated by Django 3.0.2 on 2020-03-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20200301_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterDataSet',
            new_name='CharacterData',
        ),
    ]
